#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : tornado
Version  : 6.0.1
Release  : 52
URL      : https://files.pythonhosted.org/packages/b1/7f/8109821ff9df1bf3519169e34646705c32ac13be6a4d51a79ed57f47686e/tornado-6.0.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/b1/7f/8109821ff9df1bf3519169e34646705c32ac13be6a4d51a79ed57f47686e/tornado-6.0.1.tar.gz
Summary  : Clone of a C64 game, the goal is to destroy the opponent's house with certain weather phenomena
Group    : Development/Tools
License  : Apache-2.0
Requires: tornado-license = %{version}-%{release}
Requires: tornado-python = %{version}-%{release}
Requires: tornado-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
Running the Tornado Facebook example
====================================
To run this example, you must register a Facebook application with a
Connect URL set to the domain the this demo will be running on
(i.e. http://localhost:8888/ by default).  The API key and secret
for this application must be passed on the command line:

%package license
Summary: license components for the tornado package.
Group: Default

%description license
license components for the tornado package.


%package python
Summary: python components for the tornado package.
Group: Default
Requires: tornado-python3 = %{version}-%{release}

%description python
python components for the tornado package.


%package python3
Summary: python3 components for the tornado package.
Group: Default
Requires: python3-core

%description python3
python3 components for the tornado package.


%prep
%setup -q -n tornado-6.0.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1551669633
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/tornado
cp LICENSE %{buildroot}/usr/share/package-licenses/tornado/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/tornado/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
