#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : tornado
Version  : 4.5.1
Release  : 25
URL      : https://pypi.debian.net/tornado/tornado-4.5.1.tar.gz
Source0  : https://pypi.debian.net/tornado/tornado-4.5.1.tar.gz
Summary  : Tornado is a Python web framework and asynchronous networking library, originally developed at FriendFeed.
Group    : Development/Tools
License  : Apache-2.0
Requires: tornado-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
Running the Tornado Facebook example
====================================
To run this example, you must register a Facebook application with a
Connect URL set to the domain the this demo will be running on
(i.e. http://localhost:8888/ by default).  The API key and secret
for this application must be passed on the command line:

%package python
Summary: python components for the tornado package.
Group: Default

%description python
python components for the tornado package.


%prep
%setup -q -n tornado-4.5.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1492722323
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1492722323
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
